name: Release Picpocket

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Clickable
        run: |
          docker pull clickable/ci-ut24.04-1.x-amd64:latest

      - name: Build
        run: |
          docker run --env CLICKABLE_FRAMEWORK=ubuntu-touch-24.04-1.x --volume ./:/app clickable/ci-ut24.04-1.x-amd64:latest bash -c "cd /app && clickable build"

      - name: Deploy
        run: |
          docker run --env CLICKABLE_FRAMEWORK=ubuntu-touch-24.04-1.x --env OPENSTORE_API_KEY="${{ secrets.OPENSTORE_API_KEY }}" --volume ./:/app clickable/ci-ut24.04-1.x-amd64:latest bash -c "cd /app && clickable publish -- '${{ github.event.head_commit.message }}'"
